### ISSUE TITLE
[FEATURE] Disable certain devices

### ISSUE THREAD

**Issue by kopierschnitte** [copystring/ioBroker.roborock#647]
### Bug Description

Hi!
I've got a robot on a remote location without network connection to my ioBroker-Host and the adapter is therefore flooding my log with connection errors to this specific device. 

### Steps to Reproduce

Add a remote device to your Roborock account.

### Expected Behavior

Have the ability to blacklist devices by their ID.

### Debug Log

Quelle | Zeit | warn |  
-- | -- | -- | --
roborock.0 | 2024-09-11 06:41:32.665 | error | Failed to execute function createClient on robot XXXXXXXX (unknown model) Failed to create tcp client: Error: connect ETIMEDOUT 10.3.4.96:58867 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)

### Adapter Version

0.6.12

### JS-Controller Version

6.0.11

### Node.js Version

20.17.0

### Operating System

Debian ARM

**Comment by copystring** [comment]
Does the robot belong to your account or is it a shared robot from a different account?

**Comment by kopierschnitte** [comment]
It belongs to my account and isn't shared. If it matters, it's a roborock.vacuum.a70 (basically a Q7 without camera).

**Comment by copystring** [comment]
It should be possible to get this connected. I need to rework my connection logic for this.
At the moment it always tries to connect locally unless the robot is a shared one.

**Comment by kopierschnitte** [comment]
Ahh, ok. This makes sense ... but maybe a simple switch or DP like "local" true/false could do the trick?

**Comment by copystring** [comment]
Would you please test https://github.com/copystring/ioBroker.roborock/tree/dev? I implemented detection of remote devices via TCP timeout. When a TCP connection fails on the start of the adapter, the adapter assumes it's a remote device.

**Comment by kopierschnitte** [comment]
Thanks for the quick fix. Unfortunately, the error remains:

Failed to execute function createClient on robot SCrfx2l70B92SSnpPvzkQ (unknown model) Failed to create tcp client: Error: connect ETIMEDOUT 10.3.4.96:58867 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16

**Comment by copystring** [comment]
This what happens with bad coding 🤦‍♂️
Please try the new dev.

**Comment by kopierschnitte** [comment]
Well, don't see any bad coding in your great adapter! 👍 
Your fix seems to work. Thanks!

Please let me observe it for a few days. I will open the issue again if I see any problems.
